acls:
-   acls:
    -   aces:
        -   grant: permit
            sequence: 10
            source:
                address: 12.12.12.0
                wildcard_bits: 0.0.0.255
        -   grant: deny
            sequence: 20
            source:
                address: 13.13.13.0
                wildcard_bits: 0.0.0.255
        -   grant: deny
            sequence: 30
            source:
                address: 0.0.0.0
                wildcard_bits: 0.0.0.255
        acl_type: standard
        name: '49'
    -   aces:
        -   grant: permit
            sequence: 10
            source:
                address: 192.168.35.0
                wildcard_bits: 0.0.0.255
        acl_type: standard
        name: GS_NAT_ACL
    -   acl_type: extended
        name: meraki-fqdn-dns
    afi: ipv4
